sigstore/sigstore

cmd/cli/app/root.go, main.go
=> Missed a couple of renames

cmd/cli/app/root.go, cmd/cli/app/sign.go, cmd/cli/main.go, go.mod, main.go, pkg/x509pkg/x509pkg.go
=> Project Rename

cmd/sign.go, pkg/keymgmt/keymgmt.go
=> Fix lint errors

cmd/root.go, cmd/sign.go
=> Bind flags with PreRun

COPYRIGHT.txt
Add year and specify "The Sigstore Authors" as copyright holder
=> Update copyright statement

pkg/signature/payload/payload.go, pkg/signature/payload/payload_test.go, pkg/signature/util.go
* Verifies the `Type` of the deserialized image signature payload if we're expecting a Cosign signature payload
* Makes things more descriptive for users, e.g. `payload.Cosign` (instead of `payload.Image`) and `payload.SimpleContainerImage` (instead of `payload.Simple`)
=> Rename signature payloads to be more descriptive for users

pkg/signature/ecdsa.go, pkg/signature/generic.go, pkg/signature/iface.go, pkg/signature/rsa.go, pkg/signature/sv_test.go, pkg/signature/util.go, pkg/signature/util_test.go
=> Signers should return the payloads which were actually signed

.github/workflows/verify.yml
Followup from this discussion https://github.com/sigstore/cosign/pull/230#discussion_r610770964
sorry about that, my fault
/assign @ahmetb
=> ci/boilerplate: fix bolierplate check

.github/workflows/go.yml, go.mod, go.sum
- update go version to use go1.16
=> go: update go version to use 1.16.x

cmd/sign.go
=> Leverage the `signature` package for signing

CODEOWNERS
=> Implement code owners

pkg/signature/rsa.go
=> use RSA-PSS instead of RSA-PKCS#1 v1.5 signature scheme

cmd/root.go
=> change to rekor.sigstore.dev

go.mod, go.sum, pkg/tlog/tlog.go
=> Bump rekor for the new API changes.

pkg/oauthflow/flow_test.go, pkg/oauthflow/interactive.go
I've tested that this works with dex.
=> Allow the OOB authentication flow when we can't open a browser.

go.mod, go.sum
=> Bump rekor.

cmd/sign.go
=> Also output the signature if required

pkg/signature/kms/gcp/client.go
=> stop using signerverifier to get access to publickeyprovider

.github/workflows/go.yml
=> update github actions to latest versions

.github/workflows/go.yml, pkg/oauthflow/interactive.go
Fixes: #113 
```release-note
```
=> pass by reference instead of pointer so correct redirect_uri is known

README.md
I found the use of "inc" here confusing at a glance, particularly without a period indicating an abbreviation, and followed by a non-capitalized non-standard term. I see no reason not to just spell the whole word there. I also fixed a typo. (I acknowledge this is a pretty trivial PR, but it bugged me as a visitor.)
=> Fix typo/readability

.github/workflows/codeql.yml, .github/workflows/e2e_test.yml, .github/workflows/test.yml, .github/workflows/verify.yml
Make tests more easily readable by modularise into specific
roles (inline with rekor/ cosign ..)
It also adds CodeQL checks
=> Modularise CI

README.md
=> Update readme in anticipation of 1.0

pkg/signature/kms/hashivault/client.go
Signed-off-by: Russell Brown <rjbrown57@gmail.com>
Fixes https://github.com/sigstore/cosign/issues/890
* Use regex instead of trimPrefix to fix signing
* Introduce environment variable VAULT_KEY_PREFIX to allow setting of which key version to verify with. If not specified will default to "vault:v1:"
=> (fix): Fix vault integration to work with rotated keys

pkg/signature/dsse/dsse.go
=> also expose the wrapped verifier in `VerifierAdapter`

pkg/signature/kms/aws/signer.go, pkg/signature/kms/azure/signer.go, pkg/signature/kms/gcp/client.go, pkg/signature/kms/hashivault/signer.go
These weren't present in golint, but started showing up in revive.
Signed-off-by: Dan Lorenc <lorenc.d@gmail.com>
Fixes
```release-note
```
=> Fix revive lint warnings.

README.md, test/fuzz/README.md
Included a basic readme for fuzzing.
=> Docs for Fuzzing

test/fuzz/signature/signature.go
=> Fuzzing for RSAPASS

test/fuzz/signature/signature.go
=> Fuzz - Fixes nil data

Makefile, test/fuzz/dsse/fuzz.go, test/fuzz/go.mod, test/fuzz/go.sum
Moved the DSSE to fuzz dir to avoid this error
https://github.com/google/oss-fuzz/runs/4646738810?check_suite_focus=true
=> Moved dsse to fuzz dir

test/fuzz/signature/signature.go
Fixed the issue https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=42466
=> Fuzz - Fixed the panic that was caused by incorrect data

.github/workflows/e2e_test.yml, .github/workflows/test.yml, go.mod, go.sum
Replaces #296.
Signed-off-by: Dan Lorenc <lorenc.d@gmail.com>
Fixes
```release-note
```
=> Bump hashicorp vault to 1.4.0.

.github/workflows/reusable-release.yml
Signed-off-by: Kenny Leung <kleung@chainguard.dev>
This is a reusable GitHub Action workflow that can be used by the Cosign|Rekor|Fulcio repos for cutting releases.
The workflow does nothing by itself, and needs to be used in another workflow for it to work.
Based off of existing workflow, https://github.com/sigstore/fulcio/blob/main/.github/workflows/cut-release.yml
@cpanato please take a look when you get a chance. thanks
Fixes
Works toward fixing https://github.com/sigstore/public-good-instance/issues/50
```release-note
```
=> Add a reusuable GitHub Action workflow for cutting releases.

README.md
Submitted the OpenSSF Best Practices badge requirements and got 81%
```release-note
OpenSSF Best Practices badge requirements met.
```
=> Included OpenSSF Best Practices badge

pkg/cryptoutils/certificate_test.go, pkg/oauthflow/device_test.go, pkg/oauthflow/pkce.go, pkg/oauthflow/pkce_test.go, pkg/signature/dsse/dsse_test.go, pkg/signature/dsse/multidsse.go, pkg/signature/kms/aws/client.go, pkg/signature/kms/azure/client.go, pkg/signature/kms/azure/signer.go, pkg/signature/kms/gcp/client.go, pkg/signature/kms/gcp/signer.go, pkg/signature/kms/hashivault/client.go, pkg/signature/kms/hashivault/e2e_test.go, pkg/signature/kms/hashivault/signer.go, pkg/signature/kms/kms.go, pkg/signature/payload/payload.go, pkg/signature/payload/payload_test.go, pkg/signature/ssh/sign_test.go, pkg/signature/sv_test.go, pkg/signature/util.go
- fix lints found by golangci-lint
the main branch have the check failing https://github.com/sigstore/sigstore/runs/5582086106?check_suite_focus=true
n/a
```release-note
NONE
```
=> fix lints found by golangci-lint

pkg/cryptoutils/publickey.go, pkg/cryptoutils/publickey_test.go
This is useful when comparing a provided public key with a key from
another source such as a certificate.
Fixes
```release-note
Added method to check for public key equality
```
=> Add method to check for public key equality

Makefile
To be consistent, `lint` may have to install `golangci-lint` if it is not installed, as done in `sigstore/cosign`.
Fixes
```release-note
```
=> Makefile: Install golangci lint

.github/workflows/e2e_test.yml, Makefile
minor update to fix the `make test-e2e` flow
=> make target integration

.github/workflows/verify.yml, pkg/signature/kms/azure/client.go, pkg/signature/kms/hashivault/client.go, pkg/signature/kms/hashivault/e2e_test.go
=> fix uppercase err msgs to quiet golangci-lint

pkg/signature/options/digest.go
Fixes #479
```release-note
```
=> Add a warning when using WithDigest with ECDSA

pkg/oauth/interactive.go
This reverts commit ff5686c2b3f0351a5b69a677723d6aefd9f25baa.
As pointed out in https://github.com/sigstore/sigstore/pull/484#issuecomment-1150226787, this doesn't actually work 😢 
Fixes
```release-note
Autoclose behavior rolledback - this didn't actually work.
```
=> Revert "Autoclose OAuth success page after 5 seconds. (#484)"

pkg/tuf/client_test.go
Signed-off-by: Asra Ali <asraa@google.com>
* Removes requiring the target list is complete in the TUF client test. This list of targets can change during root signing events, and this test shouldn't be so fragile. Only keeps stable targets.
=> tuf: remove test that targets list is complete

pkg/oauthflow/device.go, pkg/oauthflow/device_test.go
This is blocked by the appropriate support within Dex
=> add pkce values to device code flow

pkg/cryptoutils/publickey.go, pkg/cryptoutils/publickey_test.go
This reverts commit 44be03d7c42ebfd7c73b5d5f4e6dd5aef1901b16.
Revert incorrect fix. Apologies for the confusion.
See https://github.com/sigstore/sigstore/pull/633#issuecomment-1221485757 for details
=> Revert "Fix: support certificate pem type (#633)"

pkg/cryptoutils/certificate.go, pkg/fulcioroots/fulcioroots.go, pkg/oauth/interactive.go, pkg/oauth/internal/token.go, pkg/oauth/oidc/interactive.go, pkg/oauthflow/device.go, pkg/signature/dsse/adapters.go, pkg/signature/options/context.go, pkg/signature/payload/payload.go, pkg/signature/ssh/armor.go
=> Package descriptions for all TODOs

pkg/fulcioroots/fulcioroots.go
This creates 2 new funcs (*WithCertPool) that allows clients to pass in an existing CertPool (e.g. the System pool) to allow creating of combined pools that include the Fulcio cert.
Part of https://github.com/sigstore/gitsign/issues/166
Signed-off-by: Billy Lynch <billy@chainguard.dev>
Adds GetWithCertPool and GetIntermediatesWithCertPool to allow appending Fulcio certs to existing CertPools.
=> fulcioroots: Allow appended Fulcio roots to an existing CertPool.

.github/workflows/reusable-release.yml
I am a Cosign owner and occasionally need to cut a Cosign release.
Signed-off-by: Zachary Newman <zjn@chainguard.dev>
=> Add @znewman01 to reusable-release

.github/workflows/codeql.yml, .github/workflows/e2e_test.yml, .github/workflows/reusable-release.yml, .github/workflows/test.yml, .github/workflows/verify.yml, .golangci.yml, pkg/signature/payload/payload_test.go
=> update to use go1.20

pkg/signature/kms/azure/client.go, pkg/signature/kms/azure/signer.go
This adds additional EC algorithms supported by Azure's KMS offering Key Vault. See https://learn.microsoft.com/en-us/azure/key-vault/keys/about-keys-details for all supported keys and details.
I've tested this branch with a private repository using the added algorithms to confirm these updates fix the issue.
=> Add additional EC algorithms supported by Azure KMS

pkg/tuf/client_test.go
The following PR updates the list of TUF targets used for testing in client_test.go.
Updated the list of TUF targets in pkg/tuf/client_test.go
=> chore: update TUF targets list in client_test.go

pkg/signature/ssh/sign.go
=> Fix error condition for ssh

.github/dependabot.yml, .github/workflows/test.yml, go.mod, go.sum, hack/tools/go.mod, pkg/signature/kms/aws/go.mod, pkg/signature/kms/aws/go.sum, pkg/signature/kms/azure/go.mod, pkg/signature/kms/azure/go.sum, pkg/signature/kms/gcp/go.mod, pkg/signature/kms/gcp/go.sum, pkg/signature/kms/hashivault/go.mod, pkg/signature/kms/hashivault/go.sum, test/fuzz/go.mod
- Update go.mod and dependabot config
to fix: https://github.com/sigstore/sigstore/pull/1183
=> Update go.mod and dependabot config

pkg/signature/kms/azure/azure_test.go, pkg/signature/kms/azure/client.go, pkg/signature/kms/azure/client_test.go, pkg/signature/kms/azure/go.mod, pkg/signature/kms/azure/go.sum
This updates the Azure KMS client so users can optionally provide a specific key version. It also updates the SDK, which includes some small changes that do not impact how the client is used. I tested these changes locally with a private repository.
=> Allow the user to optionally pass a Key Vault key version, update the SDK

pkg/oauthflow/flow_test.go
since `getCode` runs in a separate goroutine, it is possible that the check of `gotErr == nil` will happen before the message is read from the channel and written back to the goroutine that is checking the value. This PR changes the value to be explicitly passed via a `chan` and ensure there is consistent sequencing. This doesn't happen in real-world usage because the browser doing the OAuth dance is a separate process from the backend.
=> fix race condition in unit test

.github/workflows/reusable-release.yml
=> hide warning from setup-gcloud

README.md
Fixes: https://github.com/sigstore/sigstore/issues/1262
=> Update link to SECURITY.md

pkg/signature/kms/azure/integration_test.go
This adds an integration test for VerifySignature, which was missing. It also cleans up some other tests and print statements.
=> Add VerifySignature integration test and cleanup other tests and print statements

.github/workflows/e2e_test.yml, .github/workflows/sync-module-tags.yaml, .github/workflows/test.yml, .github/workflows/verify.yml, go.mod, hack/tools/go.mod, pkg/signature/kms/aws/go.mod, pkg/signature/kms/azure/go.mod, pkg/signature/kms/gcp/go.mod, pkg/signature/kms/hashivault/go.mod, test/fuzz/go.mod
- upgrade ci to run go1.21 and set min go version to 1.20
=> upgrade ci to run go1.21 and set min go version to 1.20

test/e2e/e2e-test.sh
=> ensure e2e tests run on new KMS modules

POLICY.md
=> Create POLICY.md for algs/KMS

.github/dependabot.yml
=> Group minor/patch updates for dependabot

.github/dependabot.yml
=> Update dependabot to weekly

pkg/signature/kms/aws/client.go
Support for ARN in AWS China uses arn:aws-cn:kms:[region]:[account_id]:key/[kms_id].
https://docs.aws.amazon.com/IAM/latest/UserGuide/reference-arns.html
The following are the supported partitions:
aws - AWS Regions
aws-cn - China Regions
aws-us-gov - AWS GovCloud (US) Region
=> Added kms support for AWS China region

pkg/tuf/usage_type_test.go
=> Remove comma in test output

pkg/signature/ecdsa.go, pkg/signature/ecdsa_test.go
fyi @laurentsimon 
Closes #1685
=> add support for verifying IEEE P1363 encoded ECDSA sigs

.github/workflows/codeql.yml, Makefile
=> update Makefile so CodeQL covers all go files

test/e2e/dexidp.Dockerfile, test/e2e/localstack.Dockerfile, test/e2e/vault.Dockerfile
Fixes: https://github.com/sigstore/sigstore/security/code-scanning/45
Fixes: https://github.com/sigstore/sigstore/security/code-scanning/43
Fixes: https://github.com/sigstore/sigstore/security/code-scanning/47
=> pin container images to quiet scorecard alert

.github/workflows/codeql.yml, .github/workflows/e2e_test.yml, .github/workflows/fuzzing.yml, .github/workflows/verify.yml
=> set gh action perms

.github/workflows/test.yml, .github/workflows/verify.yml, go.mod, hack/tools/go.mod, pkg/oauth/oidc/interactive.go, pkg/oauthflow/interactive.go, pkg/signature/kms/aws/go.mod, pkg/signature/kms/azure/go.mod, pkg/signature/kms/gcp/go.mod, pkg/signature/kms/hashivault/go.mod, test/fuzz/go.mod
- update to go1.22.7
- update ci jobs
=> update to go1.22.7 and ci job

pkg/signature/kms/azure/README.md, pkg/signature/kms/azure/client.go, pkg/signature/kms/azure/client_test.go
This replaces custom authentication code used in the Azure KMS client with `azidentity.NewDefaultCredential`, which will try each type of authentication method.
=> Replace custom auth code with `azidentity.NewDefaultCredential` for Azure KMS client

.github/workflows/e2e_test.yml, Makefile
Adds Windows, Mac, and Ubuntu testing for the cliplugin's `make test-signer-program`.
https://github.com/sigstore/sigstore/actions/runs/13120139767/job/36603930059#step:4:23
**Testing**
On Windows, make, mingw and git need to be installed to run the `make` commands.
No new documentation.
=> cliplugin: add windows ci testing

.github/workflows/verify.yml, .golangci.yml, Makefile, pkg/signature/kms/aws/client.go, pkg/signature/kms/azure/client.go, pkg/signature/kms/azure/client_test.go, pkg/signature/kms/azure/signer.go, pkg/signature/kms/gcp/client.go, pkg/signature/kms/hashivault/client.go
@haydentherapper @ramonpetgrave64 fyi
Fixes: #1957
=> chore: fix lint issues, run lint across all submodules

pkg/signature/algorithm_registry.go
=> pkg/signature: fix RSA PSS 3072 key size in algorithm registry

POLICY.md
This points producers to the interface documentation and example, and notes we will not accept new providers in-tree.
=> Update KMS policy for new plugin interface

go.mod, go.sum, pkg/signature/tink/doc.go, pkg/signature/tink/tink.go, pkg/signature/tink/tink_test.go
Copy in the tink package from Rekor v1 so that it can be used by other services.
Relates to https://github.com/sigstore/rekor-tiles/issues/9
=> Add tink package

.github/workflows/verify.yml, .golangci.yml, pkg/signature/ecdsa.go, pkg/signature/ecdsa_test.go, pkg/signature/kms/fake/signer.go, pkg/signature/kms/gcp/client.go, pkg/signature/rsapkcs1v15_test.go, pkg/signature/rsapss_test.go, pkg/signature/tink/tink.go, pkg/signature/tink/tink_test.go
=> Update linter to v2

POLICY.md
We now point to the algorithm registry as the source of truth for supported algorithms. This also updates the names of the NIST-standardized algorithms.
I've left the thoughts on PQC algs in the policy still, though we may move it out to the alg registry spec.
=> Update signing algorithm policy

go.mod, pkg/signature/tink/tink.go, pkg/signature/tink/tink_test.go
From https://github.com/sigstore/fulcio/pull/2024. Will update Fulcio and other Sigstore repos to use this shared implementation.
=> Update to use Tink v2.3.0 API

pkg/signature/kms/azure/signer.go
per https://github.com/sigstore/sigstore/issues/2065
This pull request adds the context handling to the Azure SignerVerifier implementation. It ensures to use the context passing from opts for context-based configurations.
=> Add context from opts to Azure signer

test/cliplugin/localkms/implementation.go
fyi @arthurus-rex
Fixes: #2130
=> use more generic PEM parser within localkms example
