README.md, cmd/cli/app/sign.go, config/config.go, pkg/x509pkg/x509pkg.go
=> User can use toml config for cert details

pkg/keymgmt/keymgmt.go, pkg/keymgmt/keymgmt_test.go
PubK requires MarshalPKIXPublicKey and returning as []uint8
=> Return PubK in correct type

cmd/sign.go, pkg/httpclient/httpclient.go
Previously we returned the certs, however this affords us less
control to perform later actions based on http specific http
status codes.
For example, we may want to rig in a retry handler or pretty
print failures specific to an end users UX.
The change instead returns the error type, which we can then
case type to meaningful error handling.
=> Return the response so we can handle specific status codes

Makefile, cmd/version.go
- Add a version command
normal
```
$ ./sigstore version
GitVersion:    e614ea3-dirty
GitCommit:     e614ea31ba831c31d318823dfa7db9b2c762f44c
GitTreeState:  dirty
BuildDate:     '2021-04-05T17:27:49Z'
GoVersion:     go1.16.1
Compiler:      gc
Platform:      darwin/amd64
```
in JSON:
```
./sigstore version -j
{
"GitVersion": "e614ea3-dirty",
"GitCommit": "e614ea31ba831c31d318823dfa7db9b2c762f44c",
"GitTreeState": "dirty",
"BuildDate": "'2021-04-05T17:27:49Z'",
"GoVersion": "go1.16.1",
"Compiler": "gc",
"Platform": "darwin/amd64"
}
```
Fixes: https://github.com/sigstore/sigstore/issues/30
=> cmd: add version command

pkg/keymgmt/keymgmt.go, pkg/signfile/signfile.go
=> Use `crypto.PublicKey` in favor of `*ecdsa.PublicKey`

pkg/kms/gcp/gcp.go, pkg/kms/gcp/gcp_test.go
This means we don't need to give KMS key management IAM permissions
if you can specify the full thing.
=> Allow specifying the full key version.

README.md
=> Better define sigstores purpose

.github/workflows/go.yml, .golangci.yml, Makefile, pkg/kms/kms.go, pkg/oauthflow/device.go, pkg/oauthflow/device_test.go, pkg/oauthflow/flow.go, pkg/signature/ecdsa.go, pkg/signfile/signfile.go
=> remove gosec since it is handled by golangci-lint

pkg/signature/ed25519.go, pkg/signature/ed25519_test.go
We can use this in tekton chains! 
Signed-off-by: Priya Wadhwa <priyawadhwa@google.com>
=> Add support for ed25519 based keys

cmd/sign.go, go.mod, pkg/oauthflow/device.go, pkg/oauthflow/flow.go, pkg/oauthflow/flow_test.go, pkg/oauthflow/interactive.go, pkg/signature/ed25519.go
This is part of the federation/SPIRE/keyless flows for machines.
=> Add support for static identity tokens supplied directly by the caller.

pkg/kms/hashivault/hashivault.go, test/e2e/kms/vault_test.go
Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>
I have a problem with storing keys in the Vault transit engine. cosign waits for me to enable `Vault Transit Secret Engine` at path `transit/`, but in Vault, I don’t have to enable secret engines at its default paths, so, I can override this behavior by using -path option while enabling it. So, in the scenario I have been enabled Transit Secret Engine at a different path, cosign throws an error like the following:
if you want to reproduce that error above, you can type the following commands:
```
$ vault server -dev -dev-root-token-id root
$ export VAULT_ADDR="http://localhost:8200"
$ export VAULT_TOKEN="root"
$ vault secrets enable -path=keystore transit
$ cosign generate-key-pair -kms hashivault://test-key
```
This PR is …
=> enable transit secret engine at another path

cmd/sign.go
Fulcio does not populate the Subject, so let's return the serial
instead.
=> cert.Subject is not populated, return serial instead

pkg/cryptoutils/certificate.go
Break condition was trying to match an empty array with nil
This resulted in no break condition and the error working down
to `error during PEM decoding`
Instead match on an empty length
=> Fix for Error: error during PEM decoding

cmd/sign.go
Also remove `signingCert.Subject` which returns an empty result
=> Add formatted URL for rekor entry

pkg/cryptoutils/certificate.go, pkg/signature/ecdsa.go, pkg/signature/ed25519.go, pkg/signature/ed25519_test.go, pkg/signature/kms/gcp/client.go, pkg/signature/kms/gcp/signer.go, pkg/signature/kms/hashivault/signer.go, pkg/signature/kms/kms.go, pkg/signature/publickey.go, pkg/signature/rsapkcs1v15.go, pkg/signature/rsapss.go, pkg/signature/signer.go, pkg/signature/signerverifier.go, pkg/signature/verifier.go
Given the requirements of cosign, I split out the PublicKey() method into its own interface such that it can be implemented by both signers and verifiers (since both have a public key).
Also small fixes including:
- ed25519 passes by value rather than pointer for public/private keys
- adds SupportedAlgorithms() and DefaultAlgorithm() method for KMS SignerVerifiers (ideal for use in CreateKey() method)
=> Add PublicKeyProvider interface

pkg/utils/filehandler.go
While doing the fulcio release notice the mime-type `application/x-executable` was not supported. adding this the list of supported mime-types
=> filehandler: add application/x-executable to supported mimetype

pkg/signature/kms/gcp/signer.go
=> compute crc over digest instead of message

pkg/oauthflow/interactive.go
=> We should use the client ID from the oauth config, not viper.

pkg/signature/ed25519.go, pkg/signature/ed25519_test.go, pkg/signature/sv_test.go
stdlib assumes `ed25519.(Public, Private)Key` by value ([example](https://golang.org/pkg/crypto/x509/#MarshalPKCS8PrivateKey))
=> Don't use pointers for ed25519 keys

.github/workflows/go.yml, go.mod, go.sum, pkg/signature/kms/aws/aws_test.go, pkg/signature/kms/aws/client.go, pkg/signature/kms/aws/signer.go, pkg/signature/kms/kms.go, pkg/signature/options.go, pkg/signature/options/remoteverification.go, test/e2e/docker-compose.yml, test/e2e/e2e-test.sh, test/e2e/kms/aws_test.go, test/e2e/kms/vault_test.go
This adds AWS as a supported KMS backend.
=> AWS KMS Support

pkg/cryptoutils/privatekey.go
=> ENCRYPTED COSIGN PRIVATE KEY -> ENCRYPTED SIGSTORE PRIVATE KEY

.gitignore, Makefile, README.md
small update on the makefile
when running `make pkg` was getting
```
$ make pkg
make: `pkg' is up to date.
```
so nothing actually ran :/
also update the readme and removed the part `signing CLI tool` which is not true anymore
=> small update in the makefile

pkg/signature/ecdsa.go
After discussion regarding also. defaulting to P-384 in Cosign, we decided to stick with P-256 due to broad popularity, support, and performance. https://malware.news/t/everyone-loves-curves-but-which-elliptic-curve-is-the-most-popular/17657
Not _too_ opinionated, but would prefer to err on the side of consistency unless there's a good reason why the default was change to P-384 in the first place
=> default to P-256 curve again

go.mod, pkg/signature/kms/hashivault/client.go
There is a concept called [Token Helpers](https://www.vaultproject.io/docs/commands/token-helper) in Vault. By default, the Vault CLI will store the generated token on disk in the `~/.vault-token` file. So, I realized that even though we could not set the `VAULT_TOKEN` env variable, we can still obtain the Vault token from the file with the help of this feature. So, this PR will add that support to the Vault client initialization process.
Btw, this is just an idea, so please feel free to comment it out.
=> leverage Vault token helpers approach while obtaining Vault token

pkg/signature/kms/hashivault/client.go
The environment variable TRANSIT_SECRET_ENGINE_PATH is not always used.
Some operations are hardcoded to "transit/". Users with a transit backend mounted with a non default path might not be able to use it.
=> Transit backend path is hardcoded for some operations of the KMS Vault client

go.mod, go.sum, pkg/signature/dsse/dsse.go, pkg/signature/dsse/dsse_test.go
Switches from using `github.com/in-toto/in-toto-golang/pkg/ssl` to `github.com/secure-systems-lab/go-securesystemslib/dsse`.
N/A.
```release-note
Uses new provider for DSSE.
```
=> Switch DSSE provider to go-securesystemslib

test/e2e/docker-compose.yml
e2e tests are failing due to a localstack bug. (`localstack/localstack:latest` actually reflects localstack's master branch, not latest release). This pins to a release that is known to work.
Fixes #112 
```release-note
NONE
```
=> Pin localstack in e2e tests (fixes #112)

.github/workflows/e2e_test.yml, .github/workflows/go.yml, go.mod, go.sum, pkg/oauthflow/flow.go, pkg/oauthflow/interactive.go, test/e2e/docker-compose.yml, test/e2e/e2e-test.sh, test/e2e/oauthflow/dex-config.yml, test/e2e/oauthflow/oauth_test.go
Add the OpenID flow sequence as an integration test. This allows us to test the flow, including the browser grant request.
=> Integration tests for dex / OIDConnect

pkg/signature/payload/payload.go
Right now Chains is using its own custom `SimpleSigning` struct for container images, which is marshaling JSON differently from how cosign does it. I want to copy cosign and use this library in chains as well, exposing this function should make it easier to implement.
Signed-off-by: Priya Wadhwa <priyawadhwa@google.com>
-->
```release-note
NONE
```
=> Make SimpleContainerImage struct accesible for tekton chains

pkg/signature/kms/azure/client.go, pkg/signature/kms/azure/signer.go
There were two issues: double hashing and the wrong signature formats.
We already hash the contents in SignMessage using a configurable
hash function, so we don't need this one here.
The other issue was caused by azure returning and expecting a raw byte sequence
of R||S concatenated, rather than an ASN.1 sequence. Big thanks to mwielgoszewski
for providing the tips and POC.
Signed-off-by: Dan Lorenc <lorenc.d@gmail.com>
Fixes
```release-note
```
=> Fix the azure KMS provider

pkg/oauthflow/flow.go, pkg/oauthflow/interactive.go
Suggestion:
Adding interactive flows for each specific  identity provider, allowing users to skip the main idp selection page.
I think one less click can improve the UX a bit.
Further UX improvement is gained when browser uses a default idp account the user does may not need to interactively intervene at all.
Such psodo-auto flow may also be valuable in automation uses cases, for example a git hook signing SLSA  provenance.
Hope this helps .
mikey strauss
=> Idp specific default flows

pkg/signature/dsse/dsse.go
This allows us to explicitly handle `go-securesystemslib/dsse` envelopes.
```release-note
NONE
```
=> expose `innerWrapper` as `VerifierAdapter`

pkg/signature/ssh/README.md, pkg/signature/ssh/armor.go, pkg/signature/ssh/sign.go, pkg/signature/ssh/sign_test.go, pkg/signature/ssh/verify.go
SSH signing has started to gain momentum with support in git! We have an implementation
in rekor that works, but it probably doesn't belong there. Let's move it here and realign
it with our sigstore signing APIs.
Signed-off-by: Dan Lorenc <lorenc.d@gmail.com>
Fixes
```release-note
```
=> Move the ssh signing/verification utilities to sigstore from rekor.

.github/workflows/verify.yml
* Remove unnecessary `apt-get update` step
* `uses: golangci/golangci-lint-action@v2` to be consistent w/ the same step in `cosign`
```release-note
NONE
```
=> update lint action

go.mod, go.sum, pkg/signature/dsse/dsse.go
Upgraded go-securesystemslib from 0.1.0 to 0.2.0
Fixes this https://github.com/sigstore/sigstore/pull/175 
=> Upgraded go-securesystemslib from 0.1.0 to 0.2.0

go.mod, go.sum, pkg/signature/dsse/dsse.go
Obsoletes https://github.com/sigstore/sigstore/pull/186
```release-note
NONE
```
=> bump github.com/secure-systems-lab/go-securesystemslib to v0.3.0

pkg/signature/dsse/dsse.go, pkg/signature/dsse/dsse_test.go
Fixes #191 
```release-note
```
=> fix wrong return value in error case

pkg/signature/dsse/adapters.go, pkg/signature/dsse/dsse.go, pkg/signature/dsse/dsse_test.go, pkg/signature/dsse/multidsse.go
We have added multi sign support in the DSSE v0.3.0 library,
PR suggests a wrapper to access these signer/verifiers.
Signed-off-by: houdini91 <mdstrauss91@gmail.com>
@adityasaky
=> Dsse multi signature wrapper

pkg/signature/dsse/fuzz/fuzz.go
Fixes https://github.com/sigstore/sigstore/issues/172
=> Fuzz- Fixes the invalid UTF-8 string for DSSE

.github/workflows/codeql.yml, .github/workflows/e2e_test.yml, .github/workflows/fuzzing.yml, .github/workflows/test.yml, .github/workflows/verify.yml
Addressing https://github.com/ossf/scorecard/blob/main/docs/checks.md#pinned-dependencies
data from running: `scorecard --show-details --repo=https://github.com/sigstore/sigstore/ --checks Pinned-Dependencies --format json`:
```
{
"date": "2022-01-12",
"repo": {
"name": "github.com/sigstore/sigstore",
"commit": "4133450ec3d7ca2d997251fe80b4bbbaeb790910"
},
"scorecard": {
"version": "61a0124",
"commit": "61a01244078b61abf5a2cdced8961927661edb8c"
},
"score": 6,
"checks": [
{
"details": [
"Warn: GitHub-owned action not pinned by hash: .github/workflows/codeql.yml:35",
"Warn: GitHub-owned action not pinned by hash: .github/workflows/codeql.yml:39",
"Warn: GitHub-owned action not pinned by hash: .github/workflows/codeql.yml:43",
"Warn: GitHub-owned action not pinned by hash: …
```
=> pin actions by digest; update chrome install to use signed repo

pkg/signature/kms/hashivault/client.go, test/e2e/kms/vault_test.go
This patch fixes issue with verification command when used with HashiVault KMS.
For `verify` command: see details in: https://github.com/sigstore/cosign/issues/1301
For `verify-blob` command:
```shell
cosign verify-blob --key=hashivault://my-key --signature=file.sig <path-to-arbitrary-file>
Verified OK
```
https://github.com/sigstore/cosign/issues/1301
```release-note
Fix verification with HashiVault KMS
```
=> Fix: verify with HashiVault KMS

pkg/signature/kms/azure/README.md, pkg/signature/kms/azure/client.go, pkg/signature/kms/azure/client_test.go
This patch removes the requirement of having the environment variables `AZURE_TENANT_ID`, `AZURE_CLIENT_ID` and `AZURE_CLIENT_SECRET` set to use the Azure KMS (KeyVault).
By removing the requirement, we enable usage of MSI (Managed Service Identity) through the `NewAuthorizerFromEnvironment()` and we at the same time add support for the `NewAuthorizerFromCLI()`.
By splitting the function of calculating what method to use to it's own function , `getAuthenticationMethod()`, it's possible to test the logic separately.
We also introduce the new environment variable `AZURE_AUTH_METHOD` which if set to `environment` will use `FromEnvironment()` (may be useful for the MSI case) and if set to `cli` will use `FromCLI()`.
If nothing is defined, `FromEnvironment()` will be tested first and then …
=> KMS: Change how the Azure authentication method is handled

pkg/signature/rsapkcs1v15.go, pkg/signature/rsapkcs1v15_test.go, pkg/signature/rsapss.go, pkg/signature/rsapss_test.go
This sets the set of supported hashes to SHA256, SHA384,
and SHA512. SHA1 should not be used for RSA-PKCS#1v1.5,
as it is not collision resistant. Not an expert on this,
but technically SHA1 is acceptable for RSA-PSS due to how
the hash function is used, as part of its
"mask generation function". However, since SHA1 is not
supported by cloud KMS services, we should just remove it entirely.
SHA224 is also not supported anywhere.
RSA-PKCS#1v1.5 was not enforcing the set of hashes on load.
Fixes
```release-note
Dropped support for SHA1 and SHA224 when signing and verifying with RSA-PKCS#1-v1.5 and RSA-PSS
```
=> Drop SHA1, SHA224 for RSA-PSS/PKCS#1, enforce for RSA-PKCS#1

README.md, pkg/signature/kms/hashivault/signer.go
HashiCorp Vault is the preferred way to refer to the project. This fixes two text references (not code) references to that.
None
=> Fix minor typos for HashiCorp

pkg/cryptoutils/publickey.go, pkg/cryptoutils/publickey_test.go
This will be used by Fulcio to correctly calculate the
subject key ID (SKID), which is currently hardcoded.
nolint:gosec is required for the usage of SHA1. This is acceptable for SKID generation.
Fixes
```release-note
* Added method to calculate subject key ID from public key
```
=> Add subject key ID calculation from public key

pkg/oauthflow/flow_test.go, pkg/oauthflow/interactive.go
The OIDC token callback html page was not used.
```release-note
oauthflow.InteractiveIDTokenGetter now uses the member field html page for successful token callbacks.
```
=> Wire up html page passed in for interactive OIDC callback server

go.mod, go.sum, pkg/signature/kms/hashivault/client.go, pkg/signature/kms/hashivault/signer.go, pkg/signature/kms/kms.go, pkg/signature/options.go, pkg/signature/options/noop.go, pkg/signature/options/rpcauth.go, test/e2e/e2e-test.sh, test/e2e/kms/vault_test.go
Signed-off-by: Brandon Mitchell <git@bmitch.net>
This adds the ability to login to vault using OIDC to get a token, and removes dependencies on environment variables.
I'm using this with Spire+OIDC to use Vault as a KMS without hard coding credentials in CI. Here's what that code looks like:
```golang
...
kmsOpts := []signature.RPCOption{}
rpcAuth := options.RPCAuth{
Address: cfg.Auth.Address,
OIDC: options.RPCAuthOIDC{
Role: cfg.Auth.Role,
Path: cfg.Auth.Path,
},
}
jwtSource, err := workloadapi.NewJWTSource(
ctx,
workloadapi.WithClientOptions(workloadapi.WithAddr(cfg.Auth.Spire.Sock)),
)
if err != nil {
return err
}
svid, err := jwtSource.FetchJWTSVID(ctx, jwtsvid.Params{Audience: cfg.Auth.Spire.Audience})
if err != nil {
return err
}
rpcAuth.OIDC.Token = svid.Marshal()
kmsOpts = …
```
=> Add oidc login to vault

pkg/oauthflow/pkce.go, pkg/oauthflow/pkce_test.go
This skips the check for the `code_challenge_methods_supported` claim
within the OIDC discovery document when configured to connect to an
Azure-based OIDC provider. AFAIK, Azure OIDC does in fact support PKCE
but does not advertise this in its discovery document so this should
enable additional use cases with `cosign` and Azure.
Partially-Fixes: https://github.com/sigstore/cosign/issues/1354
=> Skip strict check on PKCE discovery claim on Azure

pkg/signature/kms/hashivault/client.go, pkg/signature/kms/hashivault/signer.go, pkg/signature/options.go, pkg/signature/options/keyversion.go, pkg/signature/options/noop.go, test/e2e/kms/vault_test.go, test/e2e/oauthflow/oauth_test.go
This adds a functional option to specify a key version to be used during signing and verification operations.
This partially addresses sigstore/cosign#1351
=> Add ability to specify key version for Hashivault

pkg/signature/kms/hashivault/client.go, pkg/signature/options.go, pkg/signature/options/keyversion.go, pkg/signature/options/noop.go, test/e2e/kms/vault_test.go
This is a follow-on to #256 that allows a caller to request the signer write the version of the vault key used to sign the artifact in a `*string`. 
This also partially addresses sigstore/cosign#1351
=> return version of Vault key via functional option

pkg/signature/kms/aws/client.go, pkg/signature/kms/azure/client.go, pkg/signature/kms/gcp/client.go, pkg/signature/kms/hashivault/client.go, pkg/signature/kms/kms.go
Clients who want to enable specific kms implementations can import (or underscore-import) specific KMS impls they want, and otherwise don't have to depend on them.
```release-note
Specific kms implementations that are needed must be explicitly imported for init-time setup.
```
=> pkg/signature/kms doesn't depend on kms impls

go.mod, go.sum, test/e2e/oauthflow/oauth_test.go
Per https://github.com/bouk/monkey/blob/master/LICENSE.md we shouldn't be using this library in our e2e OIDC testing.
There may be a more elegant way to do this without monkey patching, but this at least moves us to a library with an MIT license that is actively maintained.
=> remove unmaintained test dependency with invalid license

.github/workflows/codeql.yml
Per https://github.com/github/codeql-action#usage we need to add `security-events: write` to the CodeSQL action now that the default permissions for the sigstore org are read-only.
=> update permissions for codeql

.golangci.yml
Copy-pasted from https://github.com/sigstore/cosign/blob/main/.golangci.yml
=> Enable the same golangci-lint rules as `cosign`

.github/workflows/reusable-release.yml
we should not stream the logs from the cloudbuild to the GitHub action job to avoid any possible leaks. 
so after the job is submitted it returns and completes the task
related to https://github.com/sigstore/fulcio/runs/5536478096?check_suite_focus=true the cloudbuild ran successfully but the svc account does not have permission to stream the logs, and then it failed.
n/a
```release-note
NONE
```
=> return immediately, without waiting for the operation in progress to complete

.github/workflows/reusable-release.yml
Signed-off-by: Kenny Leung <kleung@chainguard.dev>
Make tag,key_ring,key optional for release workflow.
This is make it possible to cut releases completely automatically.
The tag will now increment the patch value by one if the release tag is
not specified.
For example:
- 1.5.9 => 1.5.10
Keyring and Key value from GCP project are now hardcoded.
Will remove the input key_ring and key when it dependent workflows are
updated to no longer specify them.
Fixes
towards fixing https://github.com/sigstore/public-good-instance/issues/50
```release-note
```
=> Make tag,key_ring,key optional for release workflow.

pkg/oauth/internal/token.go, pkg/oauth/internal/token_test.go
These helper utilities implement https://datatracker.ietf.org/doc/html/rfc6749#section-5 and are used in the creation of custom `oauth2.TokenSource`s.
Part of Fulcio-related work for https://github.com/sigstore/cosign/issues/844
```release-note
NONE
```
=> Add utilities to parse Oauth2 access token HTTP responses

pkg/oauth/oidc/interactive.go, pkg/oauthflow/device.go, pkg/oauthflow/device_test.go, pkg/oauthflow/e2e_test.go, pkg/oauthflow/flow.go, pkg/oauthflow/flow_test.go, pkg/oauthflow/interactive.go
When using certain OIDC providers, you might need to set a specific `redirect_uri`. This implementation defaults to the old mechanism setting a listener on localhost and letting the OS to pick a port if the `redirect_uri` is not set.
Fixes https://github.com/sigstore/cosign/issues/1105 and https://github.com/sigstore/cosign/issues/1311
```release-note
oauthflow: accept a pre-defined redirect_uri.
```
=> oidc: set the redirect url if needed

pkg/signature/kms/gcp/client.go, pkg/signature/kms/gcp/gcp_test.go
The resource path uses cryptoKeyVersions instead of versions. It appears
that versions has been working fine, so I'll err on the side of not
breaking existing users, and add cryptoKeyVersions as an alternative.
Fixes
```release-note
Fixed regular expression for GCP KMS key, now permitting crpytoKeyVersions in the resource path
```
=> Fix regex for matching GCP KMS key

go.mod, go.sum
- update boulder dependency to remove some syslog dependencies that affect windows build
PR in upstream is now merged: https://github.com/letsencrypt/boulder/pull/6029
cc @hectorj2f @haydentherapper @dlorenc 
After we merge this will update cosign
n/a
```release-note
NONE
```
=> update boulder dependency to remove some syslog dependencies that affect windows build

pkg/signature/kms/fake/signer.go, pkg/signature/kms/fake/signer_test.go
This allows us to test code that uses kms.Get by importing the fake KMS
package.
Fixes
```release-note
Added fake KMS signer for testing
```
=> Add fake signer that implements KMS interface

.github/workflows/reusable-release.yml
- fix if check in the release job
```
The workflow is not valid. In .github/workflows/cut-release.yml (Line: 24, Col: 11): Error from called workflow sigstore/sigstore/.github/workflows/reusable-release.yml@main (Line: 54, Col: 13): Unexpected symbol: '='. Located at position 20 within expression: inputs.release_tag = '' sigstore/sigstore/.github/workflows/reusable-release.yml@main (Line: 76, Col: 14): Unexpected symbol: '}'. Located at position 17 within expression: env.RELEASE_TAG },_TOOL_ORG=sigstore,_TOOL_REPO=${{ inputs.repo
````
n/a
```release-note
NONE
```
=> fix if check in the release job

pkg/oauth/oidc/interactive.go, pkg/oauthflow/interactive.go
I realized the RedirectURL was not reseted to `urn:ietf:wg:oauth:2.0:oob` even if a different value was set.
Fixes
```release-note
```
=> chore: set redirect URL in doOobFlow

.github/workflows/e2e_test.yml, .github/workflows/test.yml, .github/workflows/verify.yml, go.mod, hack/tools/go.mod, test/fuzz/go.mod
Update to 1.17 as 1.16 is deprecated. bump testing from 1.17 up to 1.18
Fixes
```release-note
```
=> Update to go 1.17 / 1.18

.github/workflows/test.yml
- run tests with go1.17 and go1.18
follow-up https://github.com/sigstore/sigstore/pull/374/files#r845966876
n/a
```release-note
NONE
```
=> run tests with go1.17 and go1.18

pkg/cryptoutils/certificate.go, pkg/cryptoutils/certificate_test.go
This will be used by Fulcio to support CSRs.
Fixes
```release-note
```
=> Add a helper method to parse a PEM-encoded CSR

pkg/cryptoutils/certificate.go, pkg/cryptoutils/certificate_test.go
This method comes from Fulcio and will be used by Rekor when generating
timestamping authority certificates.
Fixes
```release-note
Added method to generate RFC 5280 compliant serial numbers
```
=> Add method for generating certificate serial number

pkg/signature/kms/kms.go
Add error type for kms.Get when provider not found
N/A but helpful for [cosign#1776](https://github.com/sigstore/cosign/issues/1776)
```release-note
NONE
```
=> Add error type for kms.Get when provider not found

pkg/signature/kms/aws/client.go, pkg/signature/kms/azure/client.go, pkg/signature/kms/gcp/client.go, pkg/signature/kms/hashivault/client.go
These methods were defined in all the KMS impls, but were only actually
called in the GCP case. It's possible they were used outside this
pacekage, since they're exported, but for consistency we should ensure
the reference is valid before proceeding to make API calls.
Signed-off-by: Jason Hall <jason@chainguard.dev>
```release-note
KMS implementations all ensure the reference is valid before proceeding.
```
=> Call ValidReference in all KMS cases

pkg/oauthflow/flow.go
There were previously two identical copies of this HTML. If we decide to
improve the HTML experience, we won't want to maintain two duplicate
copies.
Signed-off-by: Jason Hall <jason@chainguard.dev>
```release-note
NONE
```
=> Remove copy of OAuth success HTML

pkg/cryptoutils/certificate.go, pkg/cryptoutils/certificate_test.go
This removes a DOS vector for services that use this method. Otherwise,
a client can provide a large PEM block to cause the service to do a
significant amount of work.
Fixes
```release-note
Added method to unmarshal certificates from a PEM block with a limit
```
=> Add method to unmarshal certificates with a limit

pkg/signature/ecdsa.go, pkg/signature/ecdsa_test.go, pkg/signature/rsapkcs1v15.go, pkg/signature/rsapss.go, pkg/signature/verifier.go, pkg/signature/verifier_test.go
I relaxed the hash function constraints on VerifyMessage, including the
SHA1 digest as a supported function. The expectation is that
LoadVerifier will still be the primary way to set up a verifier, which
will enforce the hash function. Otherwise, LoadUnsafeVerifier will be
used to load a verifier that only supports SHA1.
Note that SignMessage will not support SHA1 still.
I also dropped SHA1 from ECDSA's supported hash functions.
Fixes
```release-note
Added support for an unsafe verifier to verify signatures that use SHA1. Only use if SHA1 is required.
```
=> Add unsafe verifier to verify signatures with SHA1 digests

pkg/signature/ecdsa.go, pkg/signature/kms/aws/e2e_test.go
- update error message for pkg/signature/ecdsa.go when checking the VerifyASN1
Fixes #472 
```release-note
NONE
```
=> update error message for pkg/signature/ecdsa.go when checking the VerifyASN1

pkg/signature/kms/gcp/client.go, pkg/signature/kms/gcp/gcp_test.go, pkg/signature/kms/gcp/signer.go
This lets the caller control authentication, in particular by providing an `option.TokenSource`.
```release-note
gcp.LoadSignerVerifier can now be passed GRPC ClientOptions
```
cc @imjasonh @dlorenc
=> Allow passing options to GCP's `LoadSignVerifier`.

pkg/oauth/interactive.go
Small QoL improvement to clean up success pages after they are no longer
needed.
Shout out to @bobcallaway for the idea!
Co-authored-by: Bob Callaway <bcallaway@google.com>
Signed-off-by: Billy Lynch <billy@chainguard.dev>
Part of #426 
```release-note
Interactive OAuth success page will now autoclose after 5 seconds.
```
=> Autoclose OAuth success page after 5 seconds.

pkg/tuf/client.go
While https://github.com/sigstore/cosign/pull/1953 resolved access to the TUF cache when running cosign in parallel, cosign now panics when running concurrent operations as threads will try to write read data to the TUF client at the same time.
Here's a sample of the crash:
```
Successfully verified SCT...
Successfully verified SCT...
Successfully verified SCT...
fatal error: concurrent map writes
goroutine 881 [running]:
runtime.throw({0x278fcc7?, 0xc000d5b290?})
/usr/lib/golang/src/runtime/panic.go:992 +0x71 fp=0xc000b34680 sp=0xc000b34650 pc=0x43a271
runtime.mapassign_faststr(0x2330a00?, 0xc000f1a000?, {0x277a539, 0xc})
/usr/lib/golang/src/runtime/map_faststr.go:212 +0x39c fp=0xc000b346e8 sp=0xc000b34680 pc=0x4151dc
github.com/theupdateframework/go-tuf/client.(*Client).getLocalMeta(0xc0 …
```
=> Lock TUF client during target loading operations

pkg/signature/kms/hashivault/client.go, pkg/signature/kms/hashivault/e2e_test.go
Fixes a panic error that occured in https://github.com/sigstore/fulcio/issues/654
Signed-off-by: Furkan <furkan.turkal@trendyol.com>
Fixes
```release-note
Fixed a panic error where vault client return empty data from transit engine
```
=> add check if transit return nil data

pkg/oauthflow/interactive.go, pkg/oauthflow/interactive_test.go
Also adds basic tests to make sure this works.
Signed-off-by: Billy Lynch <billy@chainguard.dev>
```release-note
Fixes GetOutput infinite recursion behavior for interactive oauthflow.
```
=> oauthflow: Fix recursive call for GetOutput.

.golangci.yml, pkg/oauth/oidc/interactive.go, pkg/oauthflow/interactive.go, pkg/signature/ed25519.go, pkg/signature/ed25519_test.go, pkg/signature/kms/aws/client.go, pkg/signature/kms/gcp/client.go, pkg/signature/kms/hashivault/client.go, pkg/signature/sv_test.go
Signed-off-by: Furkan <furkan.turkal@trendyol.com>
I was playing with Vault KMS and hit two different panic cases. And both of are actually casting error:
1. [keysData.(map[string]interface{})](https://github.com/sigstore/sigstore/blob/9dde75d80cf82ad42401b08165151d947cdcd538/pkg/signature/kms/hashivault/client.go#L208)
2. [latestVersion.(json.Number)](https://github.com/sigstore/sigstore/blob/9dde75d80cf82ad42401b08165151d947cdcd538/pkg/signature/kms/hashivault/client.go#L213)
I'm not so sure which cases caused this problem. So I thought It would be nice to have a [forcetypeassert](https://github.com/gostaticanalysis/forcetypeassert) analyzer in the golangci-lint.
I also had to remove the following line because forcetypeassert still complains about: `type assertion must be checked`
``` …
```
=> Keep calm and don't panic: enable and apply forcetypeassert lint rules

pkg/signature/ed25519.go, pkg/signature/ed25519_test.go
A cleanup for #522: Remove err from type cast failures
In both cases the error value is unrelated to the cast failure, and in fact guaranteed to be `nil` on that code path.
```release-note
NONE
```
=> Remove err from type cast failures

pkg/oauth/oidc/interactive.go, pkg/oauthflow/interactive.go
This is causing ci to fail e.g. https://github.com/sigstore/sigstore/runs/7435765870?check_suite_focus=true
=> fix gosec lint G112 errors

.golangci.yml, pkg/cryptoutils/password.go, pkg/cryptoutils/publickey_test.go, pkg/oauthflow/device_test.go, pkg/oauthflow/flow.go, pkg/signature/dsse/adapters.go, pkg/signature/dsse/dsse.go, pkg/signature/dsse/multidsse.go, pkg/signature/kms/aws/client.go, pkg/signature/kms/aws/e2e_test.go, pkg/signature/kms/hashivault/client.go, pkg/signature/kms/hashivault/e2e_test.go, pkg/signature/kms/hashivault/signer.go, pkg/signature/payload/payload.go, pkg/signature/ssh/sign_test.go, pkg/tuf/client.go, pkg/tuf/client_test.go, pkg/tuf/signer.go, pkg/tuf/testutils.go
Signed-off-by: Furkan <furkan.turkal@trendyol.com>
Ran `$ gofumpt -w -extra .`
```
-w	write result to (source) file instead of stdout
-extra
enable extra rules which should be vetted by a human
```
Fixes
```release-note
```
=> ci: enable gofumpt with extra

pkg/oauthflow/flow.go
When using StaticTokenGetter do not make network calls.
Signed-off-by: Ville Aikas <vaikas@chainguard.dev>
Fix Issue #600 
When using StaticTokenGetter do not use OIDC discovery so that this flow works even without network connectivity.
=> Fix issue #600. When using StaticTokenGetter do not make network calls.

pkg/oauthflow/device.go, pkg/oauthflow/device_test.go
This patch adds the ability to use the well-known OIDC configuration to discover the device authorization and token endpoints used during a device code flow to fetch an identity token. This enables support for device code flow for OIDC providers other than `oauth2.sigstore.dev`.
=> Use well-known OIDC config for device endpoints

pkg/cryptoutils/publickey.go
Closes #622
When passing a wrong public key to the verify function, it will return an unfriendly error. Instead we can just let users know they are passing the wrong public key format
Return a friendly error when an invalid key format is passed
No change in docs
=> Add a more friendly error in pubkey failure

pkg/cryptoutils/publickey.go, pkg/cryptoutils/publickey_test.go
Signed-off-by: Kenny Leung <kleung@chainguard.dev>
Change is needed to get fulcio test to pass. See https://github.com/sigstore/fulcio/runs/7935433305?check_suite_focus=true
My understanding is that CertificatePEMType is also valid. If not, tests in fulcio will need to be fixed.
https://github.com/sigstore/fulcio/blob/main/pkg/server/grpc_server_test.go#L383
=> Fix: support certificate pem type

pkg/cryptoutils/privatekey.go, pkg/cryptoutils/privatekey_test.go, pkg/cryptoutils/publickey.go, pkg/cryptoutils/publickey_test.go
This adds support for parsing RSA public and private keys, and SEC 1 EC
private keys. This should reduce unexpected format errors for library
users.
Added support for parsing PKCS#1 private and public keys, and SEC 1 private keys
=> Add support for parsing PKCS#1 priv/pub keys, SEC1 priv keys

.github/workflows/verify.yml
Lint action findings unrelated to PRs are annoying and useless, e.g. https://github.com/sigstore/sigstore/runs/8023362038?check_suite_focus=true
=> ignore pre-existing lint errors

test/fuzz/signature/fuzz_signature_test.go
Signed-off-by: naveensrinivasan <172697+naveensrinivasan@users.noreply.github.com>
- Fixed the failing fuzz test case
NONE
=> Fix : Failing Fuzz tests for FuzzRSAPSSSignerVerfier

go.mod, go.sum, pkg/fulcioroots/fulcioroots.go, pkg/tuf/client.go
Signed-off-by: Asra Ali <asraa@google.com>
* This updated go-tuf to allow support for PEM-encoded ECDSA keys, but includes a deprecated pkg to continue to support hec-encoded ECDSA keys as used in our root for a migration period.
* feat: Add support for verifying ECDSA PEM-encoded keys. Continues deprecated hex-encoded keys for backwards compat.
=> bump: update go-tuf to pull in compatibility fix

pkg/cryptoutils/certificate.go, pkg/cryptoutils/password.go, pkg/fulcioroots/fulcioroots.go, pkg/oauth/interactive.go, pkg/oauth/internal/token.go, pkg/oauth/internal/token_test.go, pkg/oauth/oidc/interactive.go, pkg/oauthflow/device.go, pkg/signature/dsse/adapters.go, pkg/signature/dsse/dsse.go, pkg/signature/dsse/multidsse.go, pkg/signature/kms/aws/client.go, pkg/signature/kms/azure/client.go, pkg/signature/kms/fake/signer.go, pkg/signature/kms/gcp/client.go, pkg/signature/kms/hashivault/client.go, pkg/signature/kms/kms.go, pkg/signature/options/context.go, pkg/signature/payload/payload.go, pkg/signature/signer.go, pkg/signature/signerverifier.go, pkg/signature/ssh/armor.go, pkg/signature/ssh/sign.go, pkg/signature/ssh/sign_test.go, pkg/signature/ssh/verify.go, pkg/signature/verifier.go, pkg/tuf/client.go, pkg/tuf/client_test.go, pkg/tuf/testutils.go
- fix lints and remove ioutils deprecations
also fix the post submit job in main branch for the golangci
=> fix lints and remove ioutils deprecations

.golangci.yml, pkg/cryptoutils/doc.go, pkg/fulcioroots/doc.go, pkg/oauth/doc.go, pkg/oauth/internal/doc.go, pkg/oauth/oidc/doc.go, pkg/oauthflow/doc.go, pkg/signature/dsse/doc.go, pkg/signature/kms/aws/doc.go, pkg/signature/kms/azure/doc.go, pkg/signature/kms/doc.go, pkg/signature/kms/fake/doc.go, pkg/signature/kms/gcp/doc.go, pkg/signature/kms/hashivault/doc.go, pkg/signature/options/doc.go, pkg/signature/payload/doc.go, pkg/signature/ssh/doc.go
=> add package docs, fix deprecated linter

pkg/oauth/oidc/interactive.go, pkg/oauthflow/interactive.go
This change does 2 things:
1. Always sets oob URL for the oob flow. Reverts 8c6a840f - w.r.t. `pkg/oauth/oidc`: this looks largely duplicative of pkg/oauthflow so we probably want to delete / merge these together in another PR - both cosign and gitsign are using oauthflow. 🤷 
2. Changes Fscanln to Fscanf - Fscanln wasn't reading values unless it received EOF, making it non-obvious that a value was successfully read (especially in gitsign where we use the TTY directly so values don't populate to stdout).
Verified this works as expected for gitsign.
Fixes #594 
🐛 Fixes OoB flow.
=> oauthflow/interactive: Fix oob flow

pkg/cryptoutils/certificate.go, pkg/cryptoutils/certificate_test.go
This fixes a bug where certificates with trailing newlines would not be parseable.
Fixes https://github.com/sigstore/cosign/issues/2237
Fixed bug when unmarshalling certificates with trailing newline
=> Handle certificates that end in newline

.github/workflows/test.yml, .github/workflows/verify.yml, go.mod, go.sum
Signed-off-by: Asra Ali <asraa@google.com>
=> deps: bump go-tuf to main to avoid excessive logging

pkg/signature/ecdsa.go, pkg/signature/ecdsa_test.go
An invalid curve caused a panic when verifying. Note that this does not affect Rekor or Fulcio. In both cases, an invalid curve will be caught when unmarshalling the PKIX public key, which checks for curve validity.
Caught by OSS-Fuzz!
=> Handle invalid elliptic curve gracefully when verifying signature

pkg/tuf/client.go, pkg/tuf/client_test.go
Signed-off-by: Asra Ali <asraa@google.com>
Added a test, patched `cosign` locally, and can confirm this now works correctly with the v5 root changes.
Note: no old clients will break from this change. It's forward compatible.
It's in anticipation of a root update that we'll push to a separate repository as to not break clients who are still using this version. Clients won't break until the current repository loses lifetime: in late January next year.
=> tuf: fix on-disk cache when writing targets in subfolders

pkg/tuf/client.go, pkg/tuf/client_test.go
The mirror was reconfigured, but the URL was never reparsed, so when checking the scheme, there was a nil pointer exception. This fix simply returns early for GCS buckets.
Fixed TUF root initialization with GCS bucket. This affects anyone who uses their own TUF root hosted on GCS, and specifies the GCS bucket only by name and not by HTTP path.
=> Fix remoteFromMirror with GCS bucket

go.mod, pkg/signature/kms/gcp/client.go
- "google.golang.org/genproto/googleapis/cloud/kms/v1" is deprecated so changing to "cloud.google.com/go/kms/apiv1/kmspb"
see https://github.com/sigstore/sigstore/actions/runs/3495896059
=> update import due to deprecation

pkg/cryptoutils/sans.go, pkg/cryptoutils/sans_test.go, test/cert_utils.go
These were used by both Cosign and Fulcio, and will now be used by Rekor, so they should be in the shared library.
=> Move OtherName and SANS functions to s/s

README.md
Context: https://github.com/sigstore/sigstore-go
This text is consistent with the long-term purpose of s/s, as well as the current state. Eventually, the "Go clients" bit will develop a little more nuance :)
Signed-off-by: Zack Newman <zjn@chainguard.dev>
=> Update README to describe purpose of s/s

pkg/signature/kms/azure/client.go, pkg/signature/kms/azure/client_test.go, pkg/signature/kms/azure/signer.go
Closes https://github.com/sigstore/sigstore/issues/849
This adds support for handling HSM backed keys. Currently when the Azure KMS client tries to fetch and parse a key stored in Key Vault, it does not handle keys stored in HSMs. HSM backed keys have key types suffixed with "-HSM". This breaks when the client to tries to convert the key to a `go-jose.JSONWebKey` instance.
=> Update Azure KMS client to handle HSM backed keys

.github/workflows/scorecard.yml
The motivation for this PR is to make sigstore be warned about supply-chain security issues using Scorecard tool.
The PR adds Scorecard workflow using [sigstore/community reusable workflow](https://github.com/sigstore/community/blob/main/.github/workflows/reusable-scorecard.yml).
The PR does not add Scorecard badge to README, let me know if you would like that.
Config changes: Add Scorecard to warn about sigstore possible security issues
None.
=> Add scorecard analysis workflow

pkg/tuf/client.go, pkg/tuf/client_test.go
This changes Initialize/NewFromEnv to always check if the timestamp is expired, while still locking access to the TUF object.
Ref: https://github.com/sigstore/public-good-instance/issues/1161
=> Allow Initialize/NewFromEnv to reinitialize metadata if timestamp expired

go.mod, pkg/oauthflow/flow.go, pkg/oauthflow/flow_test.go, pkg/signature/kms/azure/client.go
https://github.com/square/go-jose/tree/master says the former is deprecated. Moving everything to /v3 will, eventually, allow callers to only contain one vendored implementation instead of up to 3.
NONE
N/A
=> Migrate from gopkg.in/square/go-jose.v2 to github.com/go-jose/go-jose/v3

pkg/signature/dsse/adapters.go, pkg/signature/dsse/adapters_test.go
https://github.com/secure-systems-lab/go-securesystemslib/commit/60bd7fdd1b0d044e01ec9692967490243bef67c3 added the `ctx` parameters during signing and verification - this PR ensures that they are used, as well as adding unit testing to ensure that the interfaces are actually correctly implemented.
* `context.Context` is now correctly used during signing and verification of DSSE envelopes
=> use provided context when signing and verifying via DSSE adapters

pkg/tuf/client.go, pkg/tuf/client_test.go
This PR silently changes the use of the sigstore public-good-instance production TUF root from calling GCS's HTTP endpoints to using the newly created CDN https://tuf-repo-cdn.sigstore.dev
=> map GCS HTTP endpoints to new CDN for sigstore public-good production TUF root

.github/workflows/verify.yml, pkg/cryptoutils/publickey.go, pkg/signature/dsse/adapters_test.go, pkg/signature/dsse/dsse.go, pkg/signature/dsse/multidsse.go, pkg/signature/kms/azure/client.go, pkg/signature/kms/azure/client_test.go, pkg/signature/kms/azure/signer.go, pkg/signature/kms/fake/signer.go, pkg/signature/kms/gcp/client.go, pkg/signature/kms/gcp/gcp_test.go, pkg/signature/kms/hashivault/client.go, pkg/signature/options/noop.go, pkg/signature/ssh/sign.go, pkg/signature/ssh/verify.go
This upgrades golangci-lint to 1.52 and fixes the unused arguments it complains about.
=> fix lint errors for unused args

pkg/signature/kms/aws/e2e_test.go, test/e2e/e2e-test.sh
=> disable HTTP connection reuse in AWS e2e tests

pkg/signature/kms/aws/go.mod, pkg/signature/kms/azure/go.mod, pkg/signature/kms/gcp/go.mod, pkg/signature/kms/hashivault/go.mod
https://github.com/sigstore/sigstore/pull/1115 split KMS providers into separate Go modules in this repo.
They use a `replace sigstore => ../../../` to allow the modules to build from locally cloned source, using the parent module's source for sigstore/sigstore module. Because this `replace` is used, the version of the module specified as a `require` doesn't matter, and was set to the non-existent pseudoversion `v0.0.0-00010101000000-000000000000`
This breaks down when the modules are used _outside_ the repo (e.g., in cosign), since the `replace` is not consulted, and the stand-in pseudoversion doesn't exist.
This change makes the `require` specify a real sigstore/sigstore release (the latest, currently), so they can be referenced outside of this local source tree.
@haydentherapper
=> have submodules specify real s/s releases

pkg/signature/payload/payload.go, pkg/signature/payload/payload_test.go
We now feature a `payload.Cosign.ClaimedIdentity` field which can be used to customize the `image.Critical.Identity.DockerReference`.
Refers to https://github.com/sigstore/cosign/pull/2984, https://github.com/containers/image/issues/1952
* Added `payload.Cosign.ClaimedIdentity` field which can be used to customize the `image.Critical.Identity.DockerReference`.
None
=> Add `Cosign.ClaimedIdentity` API

pkg/signature/kms/azure/client.go, pkg/signature/kms/azure/go.mod, pkg/signature/kms/azure/go.sum, pkg/signature/kms/azure/signer.go
Azure KMS explicitly supports a [single hash function per EC curve](https://learn.microsoft.com/en-us/azure/key-vault/keys/about-keys-details#signverify). This PR makes the Azure KMS provider infer the hash function from the key. This brings the behavior closer to that of the GCP KMS provider, and allows Fulcio to use Azure KMS with curves longer than P-256. This is an alternative to https://github.com/sigstore/fulcio/pull/1152
=> Azure KMS: Infer hash function from key

.github/workflows/verify.yml, .golangci.yml, Makefile
- update golangci-lint to v1.53.x and add depguard rules
=> update golangci-lint to v1.53.x and add depguard rules

pkg/tuf/client.go
Before the default (sha512) hash function was the only one used when comparing hashes. This commit makes the choice explicit instead of depending on go-tuf's default vaule. Now sha256 and sha512 are recognized as valid hash functions.
Also this commit does not hide the error from go-tuf's underlying methods used to verify the target's meta.
SHA256 is now a recognized hash function when verifying target metadata from a TUF repository
N/A
=> Specify hashes when comparing target meta.

pkg/signature/payload/payload.go
Branch master was renamed to main, update it directly without the help of github page redirection.
NONE
=> chore: Update the containers/image branch name

pkg/signature/kms/hashivault/client.go
* While using Tekton Chains with hashivault, if there was some misconfiguration, then it was getting panic because the error was not handled correctly
* Hence this patch handles the error before returning the value
=> Handles the error in kms/hashivault

pkg/signature/kms/hashivault/client.go
* Previously with this patch https://github.com/sigstore/sigstore/pull/1414, 
the error was handled but the order of the error was not correct, because
while using Tekton Chains with hashivault, chains controller was getting 
paniced because the order of error handled was not correct
* Hence, with this patch, error is handled correctly and also a condition is 
added to check if the item retrieved is nil or not to avoid Tekton Chains 
controller pod crashing
=> Fixes the error handling in kms/hashivault

pkg/signature/ed25519ph.go, pkg/signature/signerverifier_test.go
In https://github.com/sigstore/fulcio/issues/1388#issuecomment-1915809491 we agreed to just use ED25519 (Pure) in Fulcio. That means that in Cosign (maybe elsewhere?) we need to convert a ED25519phSignerVerifier to the Pure version, but for doing so we need access to the Private key, thus the new `ConvertToED25519` API.
* Added `ConvertToED25519` method to `ED25519phSignerVerifier` to convert the `ED2551ph` SignerVerifier to a `ED25519` one.
=> Convert ED25519phSignerVerifier to the Pure version

pkg/oauthflow/client_credentials.go, pkg/oauthflow/client_credentials_test.go, pkg/oauthflow/device_test.go, pkg/signature/kms/azure/client_test.go, pkg/signature/kms/azure/integration_test.go, test/fuzz/pem/fuzzcert_test.go, test/fuzz/signature/fuzz_signature_test.go, test/fuzz/tools.go
This PR  adds client credentials as a supported OIDC Auth Flow Provider.
Closes https://github.com/sigstore/sigstore/issues/1619
Adds a new oauthflow type, `client_credentials` that can be used by the consumers of the `sigstore` package
The change in the cosign CLI probably would? Let me know on this.
=> add client credential flow

pkg/oauth/interactive.go, pkg/oauth/oidc/interactive.go, pkg/oauth/oidc/interactive_e2e_test.go, pkg/oauthflow/flow.go
This solves a small UX friction point. It can be tested by using something that makes use of the interactive flow like `gitsign` and I've integrated those changes [here](https://github.com/sigstore/gitsign/compare/main...stgarf:gitsign:feature/autoclose-auth-page) to test with.
Update `go.mod` to contain:
`replace github.com/sigstore/sigstore => github.com/stgarf/sigstore 510ce9e`
and then run `go mod tidy`. You should be able to test out the changes. _Of note_ is that the page will not close automatically if no connectorid (for gitsign for example) is set due to the fact that the window.close API call will only succeed if the page is the first item in the window's history.
```bash
git config --local commit.gpgsign true  # Sign all commits
git config --local tag.gpgsign true  # Sign all …
```
=> Add support for autoclosing oauth flow window

pkg/tuf/client.go, pkg/tuf/usage_type.go, pkg/tuf/usage_type_test.go
closes #1645 https://github.com/sigstore/sigstore/issues/1645
Adds TSA to TUF custom metadata. 
Currently, when verifying a TSA timestamp w/ cosign you get the following:
**Warning** Custom metadata not configured properly for target tsa_leaf.crt.pem, skipping target
**Warning** Custom metadata not configured properly for target tsa_root.crt.pem, skipping target
This is due to a missing URI in TUF's customMetadata (e.g. [scaffolding](https://github.com/sigstore/scaffolding)) which will eventually be change to a ["trusted root" file](https://github.com/sigstore/root-signing/blob/55b61a38ebe380b133c224c4d0f827c5d3c98370/staging/repository/targets/acf0438a71de70bbf1813c908545281e0c4a1e3aafa2ce36b82c1cc24a9cce5169e9dcfe85c31bb4f662e94fdd9a686fa54fbbfccff1888e51ebd73924c12495.trusted_root.json# …
=> fix: adds TSA URI for customMetadata.

pkg/tuf/repository/root.json
This updates the TUF `root.json` file to match version 8, which is what the [`root-signing` repo](https://github.com/sigstore/root-signing/blob/main/repository/repository/root.json) shows as current.
Related: https://github.com/sigstore/sigstore/issues/1138
=> Update tuf root.json to version 9 from root-signing repo

pkg/tuf/client.go
The code in tuf/client.go downloads some metadata if the TUF update fails.
* The actual TUF update uses versioned URLs (e.g. "/8.root.json") but this debug code downloads different non-versioned URLS ("/root.json") so is not a very useful
* The non-versioned metadata is deprecated and likely to be removed soon
Remove the debug downloads: if better debugging info is needed, let's add that to go-tuf client update instead.
Fixes #1716
=> tuf: Remove debug metadata downloads

pkg/signature/kms/hashivault/client.go
By default, Hashicorp Vault uses pss for signing. Several (if not all) sigstore components want the signature in PKCS1 v1.5 format, and since this value is not set, they fail with verification error.
Resolves: #1735
=> Fix Hashicorp Vault KMS to use PKCS1 v1.5

pkg/oauthflow/device.go
The fix makes the Device access token request aligned with the specification : rfc8628 
Closes #1751 
This fixes a bug in Device access token request, where the request always leads to the following error : `unexpected error in device flow: invalid_client` . This happens because of the missing client_id in the request. `client_id` is a required parameter as per the [specification](https://datatracker.ietf.org/doc/html/rfc8628#section-3.4)
Also the scope is incorrectly set to a slice of string :`"openid", "email"`  instead of one single string `"openid email"`. This led to following error : `unexpected error in device flow: invalid_request`
This can be tested using `--fulcio-auth-flow=device` and with an OIDC provider ( that supports device code grant , example Keycloak) configured.
NONE
=> Fixes issue in Device access token request

.github/workflows/e2e_test.yml, pkg/oauth/oidc/interactive_e2e_test.go, pkg/oauthflow/flow.go, pkg/oauthflow/flow_test.go, test/e2e/e2e-test.sh
Added support for the `email_verified` property of an ID token to be either a boolean or string
Related to: https://github.com/sigstore/fulcio/pull/1744
Added support for the `email_verified` property of the ID token to be either a String or Boolean
-->
Added support for the `email_verified` property of the ID token to be either a String or Boolean
=> Support email_verified as a String

pkg/signature/kms/hashivault/client.go, pkg/signature/kms/hashivault/e2e_test.go
Fixes sign/verify using an ed25519 key stored in Hashicorp Vault's transit engine. Vault returns public keys in different encodings depending on the key type. In the case of ed25519, it base64 encodes the raw public key bytes.
Resolves #1810
=> Deserialize ed25519 keys from hashivault correctly

pkg/cryptoutils/publickey.go
Fix issues with using `fmt.Errorf` with dynamic
strings that do not contain any % format specifiers. Use `errors.New` instead.
The golangci-lint output in the trunk version is below - none with the PR change:
```bash
$ golangci-lint run --enable-only staticcheck ./...
pkg/cryptoutils/publickey.go:106:11: SA1006: printf-style function with dynamic format string and no further arguments should use print-style function instead (staticcheck)
return fmt.Errorf(genErrMsg(first, second, "rsa"))
^
pkg/cryptoutils/publickey.go:110:11: SA1006: printf-style function with dynamic format string and no further arguments should use print-style function instead (staticcheck)
return fmt.Errorf(genErrMsg(first, second, "ecdsa"))
^
pkg/cryptoutils/publickey.go:114:11: SA1006: printf-style function with …
```
=> fix golangci-lint issues

pkg/signature/kms/gcp/client.go
Add error check to fix CreateKey may panic when using GCP KMS
fix(kms): fix CreateKey may panic when using GCP KMS
=> fix(kms): fix CreateKey may panic when using GCP KMS

pkg/tuf/client.go
This client will no longer be updated. Use
https://pkg.go.dev/github.com/sigstore/sigstore-go/pkg/tuf
=> Mark TUF client as deprecated

.github/workflows/codeql.yml, .github/workflows/e2e_test.yml, go.mod, hack/tools/go.mod, pkg/signature/kms/aws/go.mod, pkg/signature/kms/azure/go.mod, pkg/signature/kms/gcp/go.mod, pkg/signature/kms/hashivault/go.mod, test/fuzz/go.mod
The go directive sets the minimum version of Go required to use this module. There's no need to set this to the latest semver patch version of a given Go release unless the semantics of that version of Go are required to build/test/use the module.
Notably since PR #1865 any consumers of sigstore as a library would need to bump their own go directive to 1.22.8 in order to pickup the sigstore 1.8.10 release.
Ref: https://go.dev/ref/mod#go-mod-file-go
Fixes #1879
None
N/A
=> fix: set go module directive to 1.22.0

test/fuzz/pem/fuzzcert_test.go
we need to check the concrete type and ensure it is also non-nil before bailing during a fuzzing run
=> check concrete type for non-nil to stop fuzzing crash

pkg/signature/kms/kms.go, pkg/signature/kms/kms_test.go
Fixes #1979 
**Testing**
Test against cosign
```shell
cd cosign
go mod edit -replace "github.com/sigstore/sigstore"="../sigstore"
go mod tidy
make test
```
sigstore CI tests pass.
Changes `kms.Get()` to return a `ProviderNotFoundError` when the user supplies a filepath, or an input keyResourceID that cannot be parsed by `[provider]://[key ref]`.
No new documentation.
=> fix: cliplugin: return ErrorProviderNotFound when calling Get with a path

pkg/signature/algorithm_registry.go, pkg/signature/algorithm_registry_test.go, pkg/signature/signer.go, pkg/signature/signer_test.go, pkg/signature/signerverifier.go, pkg/signature/signerverifier_test.go, pkg/signature/verifier.go, pkg/signature/verifier_test.go
As we make the Sigstore ecosystem more crypto agile, we realized that right now it is using some uncommon algorithms, like ECDSA-P384 with the SHA256 hash algorithm. However, we want the crypto-agility to be controlled and limited to a set of algorithms (see `AlgorithmRegistry`). Moreover, we want the agility to be mainly about supporting multiple key types, rather than multiple algorithms for the same key type. Thus, this PR introduces a single point where the defaults are defined.
This is going to simplify other changes across the Sigstore ecosystem, given that often enough the only information you have is the public key. Being able to derive the signing algorithm to use (or used to sign a blob) means we don't need to store or pass around any extra information (e.g. the hash function), …
=> Implement default signing algorithms based on the key type

pkg/signature/kms/azure/client_test.go
Fixes: #2035 
The intermittent failure we're seeing on line ~180 of `client_test.go` where the length of the X coordinate (ecdsaPubKey.X.Bytes()) is sometimes 32 and sometimes 31 bytes is almost certainly due to how Go's `math/big` package handles byte conversions, specifically the omission of leading zeros.
Here's the breakdown:
ECDSA Public Keys and Coordinates: An ECDSA public key consists of a point (X, Y) on an elliptic curve. In Go's `crypto/ecdsa`, the PublicKey struct stores these coordinates X and Y as *big.Int (pointers to large integers).
Curve Size (P-256): Azure Key Vault typically uses standard NIST curves like P-256 (also known as secp256r1 or prime256v1) for ECDSA keys. For P-256, the curve operates over a 256-bit field. This means that both the X and Y coordinates are …
=> change how we copy keys in azure test case

go.mod, go.sum, pkg/signature/algorithm_registry.go, pkg/signature/kms/aws/go.mod, pkg/signature/kms/aws/go.sum, pkg/signature/kms/azure/go.mod, pkg/signature/kms/azure/go.sum, pkg/signature/kms/gcp/go.mod, pkg/signature/kms/gcp/go.sum, pkg/signature/kms/hashivault/go.mod, pkg/signature/kms/hashivault/go.sum, pkg/signature/signer.go, pkg/signature/signerverifier.go, pkg/signature/util.go, pkg/signature/verifier.go, test/cliplugin/localkms/go.mod, test/cliplugin/localkms/go.sum, test/fuzz/go.mod, test/fuzz/go.sum
Add compatibility algorithms for P384/P521 to the algorithm registry, so that clients can use the `AlgorithmDetails` for their usecase.
Goes together with https://github.com/sigstore/protobuf-specs/pull/572 .
=> pkg/signature: add P384/P521 compatibility algo to algorithm registry 

pkg/signature/algorithm_registry.go, pkg/signature/algorithm_registry_test.go
This allows consumers the algorithmRegistry to move between go/protobuf-specs hash types easier.
Useful especially for rekor2, where we infer a lot of information from the signing scheme and then apply it on the log entry.
=> add proto hash algorithm to registry

pkg/signature/kms/aws/e2e_test.go, pkg/signature/kms/aws/go.mod, pkg/signature/kms/aws/go.sum
This PR replaces `github.com/aws/aws-sdk-go` with the newer `github.com/aws/aws-sdk-go-v2` in the KMS e2e tests. This change allows us to remove dependency on `github.com/aws/aws-sdk-go`.
NONE
=> Drop redundant aws-sdk-go dependency in the e2e kms tests
